FROM node:18.19.0

# ARG PORT
ARG DB_PASSWORD
ARG DB_USERNAME
ARG DB_URL
ARG DB_NAME
ARG SENDER_GMAIL_ADDRESS
ARG SENDER_GMAIL_PASSWORD
ARG PUBLIC_URL
ARG JWT_SECRET
#mongodb url
#some
# ARG MONGODB_URL

ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_USERNAME=$DB_USERNAME
ENV DB_URL=$DB_URL
ENV DB_NAME=$DB_NAME
ENV SENDER_GMAIL_ADDRESS=$SENDER_GMAIL_ADDRESS
ENV SENDER_GMAIL_PASSWORD=$SENDER_GMAIL_PASSWORD
ENV PUBLIC_URL=$PUBLIC_URL
ENV JWT_SECRET=$JWT_SECRET
# ENV MONGODB_URL=$MONGODB_URL


ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm install 

COPY . .
CMD  npm run start

EXPOSE 5050